import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "ui/dist/style.css";
import { cn } from "ui";
import { Toaster } from "ui/shadcn-ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased")}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
