import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "ui/dist/style.css";
import { cn } from "ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${inter.className} antialiased`}>{children}</body> */}
      <body className={cn(inter.className, "antialiased")}>{children}</body>
    </html>
  );
}
